# 第一題_算閏年
請定義一個函式，讀進一個年份，輸出是不是閏年。

提示：
目前使用的格里高利曆閏年規則如下：

4的倍數是可能的。
100的倍數是不可能的。
400的倍數是可能的。

# 第三題_錄取分數表格

In [5]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [42]:
score =  [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]
collage = {
"土語系": [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
"財政系": [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
"金融系": [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
"國貿系": [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
"會計系": [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
"法律系": [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
"公行系": [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
"應數系": [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
"教育系": [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
} 
marjor= ["國文", "英文", "數甲", "數乙", "物理", "化學", 
         "生物", "歷史", "地理", "公民"]

In [76]:
col = list()
for x in collage:
    a = collage[x]
    col.append(a)
col_name = list(collage.keys())

[[2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
 [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
 [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
 [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
 [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
 [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
 [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
 [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
 [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]]

In [101]:
df = pd.DataFrame(col,index=col_name,columns=marjor)

In [102]:
df

      國文   英文   數甲    數乙  物理  化學  生物  歷史  地理    公民
土語系  2.0  2.0  0.0  1.00   0   0   0   1   1  0.00
財政系  1.0  1.5  0.0  1.50   0   0   0   0   0  0.00
金融系  1.0  1.5  0.0  2.00   0   0   0   0   0  0.00
國貿系  1.5  2.0  0.0  2.00   0   0   0   0   0  0.00
會計系  1.5  2.0  0.0  2.00   0   0   0   1   1  0.00
法律系  1.0  2.0  0.0  1.00   0   0   0   1   0  1.00
公行系  1.0  1.5  0.0  1.25   0   0   0   0   0  1.25
應數系  1.0  1.0  1.5  0.00   1   1   0   0   0  0.00
教育系  1.5  2.0  0.0  1.25   0   0   0   1   1  0.00

In [103]:
a = df * score
a["加權分數"] = a[marjor].sum(1)
a

,國文,英文,數甲,數乙,物理,化學,生物,歷史,地理,公民,加權分數
土語系,173.00,158.8,0.0,96.500,0.0,0.0,0.0,78.5,82.4,0.00,589.200
財政系,86.50,119.1,0.0,144.750,0.0,0.0,0.0,0.0,0.0,0.00,350.350
金融系,86.50,119.1,0.0,193.000,0.0,0.0,0.0,0.0,0.0,0.00,398.600
國貿系,129.75,158.8,0.0,193.000,0.0,0.0,0.0,0.0,0.0,0.00,481.550
會計系,129.75,158.8,0.0,193.000,0.0,0.0,0.0,78.5,82.4,0.00,642.450
法律系,86.50,158.8,0.0,96.500,0.0,0.0,0.0,78.5,0.0,88.60,508.900
公行系,86.50,119.1,0.0,120.625,0.0,0.0,0.0,0.0,0.0,110.75,436.975
應數系,86.50,79.4,132.3,0.000,86.3,76.8,0.0,0.0,0.0,0.00,461.300
教育系,129.75,158.8,0.0,120.625,0.0,0.0,0.0,78.5,82.4,0.00,570.075

In [104]:
df1 = df
df1["加權分數"] = a["加權分數"]
df1

      國文   英文   數甲    數乙  物理  化學  生物  歷史  地理    公民     加權分數
土語系  2.0  2.0  0.0  1.00   0   0   0   1   1  0.00  589.200
財政系  1.0  1.5  0.0  1.50   0   0   0   0   0  0.00  350.350
金融系  1.0  1.5  0.0  2.00   0   0   0   0   0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00   0   0   0   0   0  0.00  481.550
會計系  1.5  2.0  0.0  2.00   0   0   0   1   1  0.00  642.450
法律系  1.0  2.0  0.0  1.00   0   0   0   1   0  1.00  508.900
公行系  1.0  1.5  0.0  1.25   0   0   0   0   0  1.25  436.975
應數系  1.0  1.0  1.5  0.00   1   1   0   0   0  0.00  461.300
教育系  1.5  2.0  0.0  1.25   0   0   0   1   1  0.00  570.075

# 迴圈跑法1

In [110]:
total = list()
for x in col_name:
    s = np.array(score)
    c = np.array(collage[x])
    total.append(np.dot(s,c)) 
total

[589.20000000000005,
 350.35000000000002,
 398.60000000000002,
 481.55000000000001,
 642.45000000000005,
 508.89999999999998,
 436.97500000000002,
 461.30000000000001,
 570.07500000000005]

In [111]:
df2 = df
df2["加權分數"] = total
df2

      國文   英文   數甲    數乙  物理  化學  生物  歷史  地理    公民     加權分數
土語系  2.0  2.0  0.0  1.00   0   0   0   1   1  0.00  589.200
財政系  1.0  1.5  0.0  1.50   0   0   0   0   0  0.00  350.350
金融系  1.0  1.5  0.0  2.00   0   0   0   0   0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00   0   0   0   0   0  0.00  481.550
會計系  1.5  2.0  0.0  2.00   0   0   0   1   1  0.00  642.450
法律系  1.0  2.0  0.0  1.00   0   0   0   1   0  1.00  508.900
公行系  1.0  1.5  0.0  1.25   0   0   0   0   0  1.25  436.975
應數系  1.0  1.0  1.5  0.00   1   1   0   0   0  0.00  461.300
教育系  1.5  2.0  0.0  1.25   0   0   0   1   1  0.00  570.075

# 迴圈跑法2

In [112]:
df3 = df
for x in col_name:
    s = np.array(score)
    c = np.array(collage[x])
    df3.loc[x,"加權分數"] = np.dot(s,c)
df3

      國文   英文   數甲    數乙  物理  化學  生物  歷史  地理    公民     加權分數
土語系  2.0  2.0  0.0  1.00   0   0   0   1   1  0.00  589.200
財政系  1.0  1.5  0.0  1.50   0   0   0   0   0  0.00  350.350
金融系  1.0  1.5  0.0  2.00   0   0   0   0   0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00   0   0   0   0   0  0.00  481.550
會計系  1.5  2.0  0.0  2.00   0   0   0   1   1  0.00  642.450
法律系  1.0  2.0  0.0  1.00   0   0   0   1   0  1.00  508.900
公行系  1.0  1.5  0.0  1.25   0   0   0   0   0  1.25  436.975
應數系  1.0  1.0  1.5  0.00   1   1   0   0   0  0.00  461.300
教育系  1.5  2.0  0.0  1.25   0   0   0   1   1  0.00  570.075